export interface CountryOption {
  code: string;
  alpha2: string;
  name: string;
  continent: string;
  isoNumeric: string;
}

/** Converte código alpha-2 em emoji de bandeira. */
export function countryFlagEmoji(alpha2: string): string {
  return alpha2
    .toUpperCase()
    .split("")
    .map((c) => String.fromCodePoint(0x1f1e6 - 65 + c.charCodeAt(0)))
    .join("");
}

export const COUNTRIES_CATALOG: CountryOption[] = [
  { code: "AFG", alpha2: "AF", name: "Afeganistão", continent: "Ásia", isoNumeric: "004" },
  { code: "ZAF", alpha2: "ZA", name: "África do Sul", continent: "África", isoNumeric: "710" },
  { code: "ALB", alpha2: "AL", name: "Albânia", continent: "Europa", isoNumeric: "008" },
  { code: "DEU", alpha2: "DE", name: "Alemanha", continent: "Europa", isoNumeric: "276" },
  { code: "AND", alpha2: "AD", name: "Andorra", continent: "Europa", isoNumeric: "020" },
  { code: "AGO", alpha2: "AO", name: "Angola", continent: "África", isoNumeric: "024" },
  { code: "SAU", alpha2: "SA", name: "Arábia Saudita", continent: "Ásia", isoNumeric: "682" },
  { code: "DZA", alpha2: "DZ", name: "Argélia", continent: "África", isoNumeric: "012" },
  { code: "ARG", alpha2: "AR", name: "Argentina", continent: "América do Sul", isoNumeric: "032" },
  { code: "ARM", alpha2: "AM", name: "Armênia", continent: "Ásia", isoNumeric: "051" },
  { code: "AUS", alpha2: "AU", name: "Austrália", continent: "Oceania", isoNumeric: "036" },
  { code: "AUT", alpha2: "AT", name: "Áustria", continent: "Europa", isoNumeric: "040" },
  { code: "AZE", alpha2: "AZ", name: "Azerbaijão", continent: "Ásia", isoNumeric: "031" },
  { code: "BHS", alpha2: "BS", name: "Bahamas", continent: "América do Norte", isoNumeric: "044" },
  { code: "BGD", alpha2: "BD", name: "Bangladesh", continent: "Ásia", isoNumeric: "050" },
  { code: "BRB", alpha2: "BB", name: "Barbados", continent: "América do Norte", isoNumeric: "052" },
  { code: "BEL", alpha2: "BE", name: "Bélgica", continent: "Europa", isoNumeric: "056" },
  { code: "BLZ", alpha2: "BZ", name: "Belize", continent: "América do Norte", isoNumeric: "084" },
  { code: "BEN", alpha2: "BJ", name: "Benin", continent: "África", isoNumeric: "204" },
  { code: "BLR", alpha2: "BY", name: "Bielorrússia", continent: "Europa", isoNumeric: "112" },
  { code: "BOL", alpha2: "BO", name: "Bolívia", continent: "América do Sul", isoNumeric: "068" },
  {
    code: "BIH",
    alpha2: "BA",
    name: "Bósnia e Herzegovina",
    continent: "Europa",
    isoNumeric: "070",
  },
  { code: "BWA", alpha2: "BW", name: "Botsuana", continent: "África", isoNumeric: "072" },
  { code: "BRA", alpha2: "BR", name: "Brasil", continent: "América do Sul", isoNumeric: "076" },
  { code: "BRN", alpha2: "BN", name: "Brunei", continent: "Ásia", isoNumeric: "096" },
  { code: "BGR", alpha2: "BG", name: "Bulgária", continent: "Europa", isoNumeric: "100" },
  { code: "BFA", alpha2: "BF", name: "Burkina Faso", continent: "África", isoNumeric: "854" },
  { code: "KHM", alpha2: "KH", name: "Camboja", continent: "Ásia", isoNumeric: "116" },
  { code: "CMR", alpha2: "CM", name: "Camarões", continent: "África", isoNumeric: "120" },
  { code: "CAN", alpha2: "CA", name: "Canadá", continent: "América do Norte", isoNumeric: "124" },
  { code: "QAT", alpha2: "QA", name: "Catar", continent: "Ásia", isoNumeric: "634" },
  { code: "KAZ", alpha2: "KZ", name: "Cazaquistão", continent: "Ásia", isoNumeric: "398" },
  { code: "CHL", alpha2: "CL", name: "Chile", continent: "América do Sul", isoNumeric: "152" },
  { code: "CHN", alpha2: "CN", name: "China", continent: "Ásia", isoNumeric: "156" },
  { code: "CYP", alpha2: "CY", name: "Chipre", continent: "Europa", isoNumeric: "196" },
  { code: "COL", alpha2: "CO", name: "Colômbia", continent: "América do Sul", isoNumeric: "170" },
  { code: "KOR", alpha2: "KR", name: "Coreia do Sul", continent: "Ásia", isoNumeric: "410" },
  {
    code: "CRI",
    alpha2: "CR",
    name: "Costa Rica",
    continent: "América do Norte",
    isoNumeric: "188",
  },
  { code: "HRV", alpha2: "HR", name: "Croácia", continent: "Europa", isoNumeric: "191" },
  { code: "CUB", alpha2: "CU", name: "Cuba", continent: "América do Norte", isoNumeric: "192" },
  { code: "DNK", alpha2: "DK", name: "Dinamarca", continent: "Europa", isoNumeric: "208" },
  { code: "EGY", alpha2: "EG", name: "Egito", continent: "África", isoNumeric: "818" },
  {
    code: "SLV",
    alpha2: "SV",
    name: "El Salvador",
    continent: "América do Norte",
    isoNumeric: "222",
  },
  { code: "ARE", alpha2: "AE", name: "Emirados Árabes", continent: "Ásia", isoNumeric: "784" },
  { code: "ECU", alpha2: "EC", name: "Equador", continent: "América do Sul", isoNumeric: "218" },
  { code: "SVK", alpha2: "SK", name: "Eslováquia", continent: "Europa", isoNumeric: "703" },
  { code: "SVN", alpha2: "SI", name: "Eslovênia", continent: "Europa", isoNumeric: "705" },
  { code: "ESP", alpha2: "ES", name: "Espanha", continent: "Europa", isoNumeric: "724" },
  {
    code: "USA",
    alpha2: "US",
    name: "Estados Unidos",
    continent: "América do Norte",
    isoNumeric: "840",
  },
  { code: "EST", alpha2: "EE", name: "Estônia", continent: "Europa", isoNumeric: "233" },
  { code: "ETH", alpha2: "ET", name: "Etiópia", continent: "África", isoNumeric: "231" },
  { code: "PHL", alpha2: "PH", name: "Filipinas", continent: "Ásia", isoNumeric: "608" },
  { code: "FIN", alpha2: "FI", name: "Finlândia", continent: "Europa", isoNumeric: "246" },
  { code: "FRA", alpha2: "FR", name: "França", continent: "Europa", isoNumeric: "250" },
  { code: "GAB", alpha2: "GA", name: "Gabão", continent: "África", isoNumeric: "266" },
  { code: "GHA", alpha2: "GH", name: "Gana", continent: "África", isoNumeric: "288" },
  { code: "GEO", alpha2: "GE", name: "Geórgia", continent: "Ásia", isoNumeric: "268" },
  { code: "GRC", alpha2: "GR", name: "Grécia", continent: "Europa", isoNumeric: "300" },
  {
    code: "GTM",
    alpha2: "GT",
    name: "Guatemala",
    continent: "América do Norte",
    isoNumeric: "320",
  },
  { code: "GUY", alpha2: "GY", name: "Guiana", continent: "América do Sul", isoNumeric: "328" },
  { code: "HTI", alpha2: "HT", name: "Haiti", continent: "América do Norte", isoNumeric: "332" },
  { code: "NLD", alpha2: "NL", name: "Holanda", continent: "Europa", isoNumeric: "528" },
  { code: "HND", alpha2: "HN", name: "Honduras", continent: "América do Norte", isoNumeric: "340" },
  { code: "HUN", alpha2: "HU", name: "Hungria", continent: "Europa", isoNumeric: "348" },
  { code: "YEM", alpha2: "YE", name: "Iêmen", continent: "Ásia", isoNumeric: "887" },
  { code: "IND", alpha2: "IN", name: "Índia", continent: "Ásia", isoNumeric: "356" },
  { code: "IDN", alpha2: "ID", name: "Indonésia", continent: "Ásia", isoNumeric: "360" },
  { code: "IRQ", alpha2: "IQ", name: "Iraque", continent: "Ásia", isoNumeric: "368" },
  { code: "IRL", alpha2: "IE", name: "Irlanda", continent: "Europa", isoNumeric: "372" },
  { code: "ISL", alpha2: "IS", name: "Islândia", continent: "Europa", isoNumeric: "352" },
  { code: "ISR", alpha2: "IL", name: "Israel", continent: "Ásia", isoNumeric: "376" },
  { code: "ITA", alpha2: "IT", name: "Itália", continent: "Europa", isoNumeric: "380" },
  { code: "JAM", alpha2: "JM", name: "Jamaica", continent: "América do Norte", isoNumeric: "388" },
  { code: "JPN", alpha2: "JP", name: "Japão", continent: "Ásia", isoNumeric: "392" },
  { code: "JOR", alpha2: "JO", name: "Jordânia", continent: "Ásia", isoNumeric: "400" },
  { code: "KEN", alpha2: "KE", name: "Quênia", continent: "África", isoNumeric: "404" },
  { code: "KGZ", alpha2: "KG", name: "Quirguistão", continent: "Ásia", isoNumeric: "417" },
  { code: "LAO", alpha2: "LA", name: "Laos", continent: "Ásia", isoNumeric: "418" },
  { code: "LVA", alpha2: "LV", name: "Letônia", continent: "Europa", isoNumeric: "428" },
  { code: "LBN", alpha2: "LB", name: "Líbano", continent: "Ásia", isoNumeric: "422" },
  { code: "LBY", alpha2: "LY", name: "Líbia", continent: "África", isoNumeric: "434" },
  { code: "LTU", alpha2: "LT", name: "Lituânia", continent: "Europa", isoNumeric: "440" },
  { code: "LUX", alpha2: "LU", name: "Luxemburgo", continent: "Europa", isoNumeric: "442" },
  { code: "MKD", alpha2: "MK", name: "Macedônia do Norte", continent: "Europa", isoNumeric: "807" },
  { code: "MDG", alpha2: "MG", name: "Madagascar", continent: "África", isoNumeric: "450" },
  { code: "MYS", alpha2: "MY", name: "Malásia", continent: "Ásia", isoNumeric: "458" },
  { code: "MLI", alpha2: "ML", name: "Mali", continent: "África", isoNumeric: "466" },
  { code: "MLT", alpha2: "MT", name: "Malta", continent: "Europa", isoNumeric: "470" },
  { code: "MAR", alpha2: "MA", name: "Marrocos", continent: "África", isoNumeric: "504" },
  { code: "MEX", alpha2: "MX", name: "México", continent: "América do Norte", isoNumeric: "484" },
  { code: "MOZ", alpha2: "MZ", name: "Moçambique", continent: "África", isoNumeric: "508" },
  { code: "MDA", alpha2: "MD", name: "Moldávia", continent: "Europa", isoNumeric: "498" },
  { code: "MCO", alpha2: "MC", name: "Mônaco", continent: "Europa", isoNumeric: "492" },
  { code: "MNG", alpha2: "MN", name: "Mongólia", continent: "Ásia", isoNumeric: "496" },
  { code: "MNE", alpha2: "ME", name: "Montenegro", continent: "Europa", isoNumeric: "499" },
  { code: "MMR", alpha2: "MM", name: "Myanmar", continent: "Ásia", isoNumeric: "104" },
  { code: "NAM", alpha2: "NA", name: "Namíbia", continent: "África", isoNumeric: "516" },
  { code: "NPL", alpha2: "NP", name: "Nepal", continent: "Ásia", isoNumeric: "524" },
  {
    code: "NIC",
    alpha2: "NI",
    name: "Nicarágua",
    continent: "América do Norte",
    isoNumeric: "558",
  },
  { code: "NGA", alpha2: "NG", name: "Nigéria", continent: "África", isoNumeric: "566" },
  { code: "NOR", alpha2: "NO", name: "Noruega", continent: "Europa", isoNumeric: "578" },
  { code: "NZL", alpha2: "NZ", name: "Nova Zelândia", continent: "Oceania", isoNumeric: "554" },
  { code: "OMN", alpha2: "OM", name: "Omã", continent: "Ásia", isoNumeric: "512" },
  { code: "PAN", alpha2: "PA", name: "Panamá", continent: "América do Norte", isoNumeric: "591" },
  { code: "PNG", alpha2: "PG", name: "Papua-Nova Guiné", continent: "Oceania", isoNumeric: "598" },
  { code: "PAK", alpha2: "PK", name: "Paquistão", continent: "Ásia", isoNumeric: "586" },
  { code: "PRY", alpha2: "PY", name: "Paraguai", continent: "América do Sul", isoNumeric: "600" },
  { code: "PER", alpha2: "PE", name: "Peru", continent: "América do Sul", isoNumeric: "604" },
  { code: "POL", alpha2: "PL", name: "Polônia", continent: "Europa", isoNumeric: "616" },
  { code: "PRT", alpha2: "PT", name: "Portugal", continent: "Europa", isoNumeric: "620" },
  { code: "GBR", alpha2: "GB", name: "Reino Unido", continent: "Europa", isoNumeric: "826" },
  { code: "CZE", alpha2: "CZ", name: "República Tcheca", continent: "Europa", isoNumeric: "203" },
  {
    code: "DOM",
    alpha2: "DO",
    name: "República Dominicana",
    continent: "América do Norte",
    isoNumeric: "214",
  },
  { code: "ROU", alpha2: "RO", name: "Romênia", continent: "Europa", isoNumeric: "642" },
  { code: "RWA", alpha2: "RW", name: "Ruanda", continent: "África", isoNumeric: "646" },
  { code: "RUS", alpha2: "RU", name: "Rússia", continent: "Europa", isoNumeric: "643" },
  { code: "SEN", alpha2: "SN", name: "Senegal", continent: "África", isoNumeric: "686" },
  { code: "SRB", alpha2: "RS", name: "Sérvia", continent: "Europa", isoNumeric: "688" },
  { code: "SGP", alpha2: "SG", name: "Singapura", continent: "Ásia", isoNumeric: "702" },
  { code: "SOM", alpha2: "SO", name: "Somália", continent: "África", isoNumeric: "706" },
  { code: "LKA", alpha2: "LK", name: "Sri Lanka", continent: "Ásia", isoNumeric: "144" },
  { code: "SWE", alpha2: "SE", name: "Suécia", continent: "Europa", isoNumeric: "752" },
  { code: "CHE", alpha2: "CH", name: "Suíça", continent: "Europa", isoNumeric: "756" },
  { code: "SUR", alpha2: "SR", name: "Suriname", continent: "América do Sul", isoNumeric: "740" },
  { code: "THA", alpha2: "TH", name: "Tailândia", continent: "Ásia", isoNumeric: "764" },
  { code: "TZA", alpha2: "TZ", name: "Tanzânia", continent: "África", isoNumeric: "834" },
  { code: "TUN", alpha2: "TN", name: "Tunísia", continent: "África", isoNumeric: "788" },
  { code: "TUR", alpha2: "TR", name: "Turquia", continent: "Ásia", isoNumeric: "792" },
  { code: "UKR", alpha2: "UA", name: "Ucrânia", continent: "Europa", isoNumeric: "804" },
  { code: "UGA", alpha2: "UG", name: "Uganda", continent: "África", isoNumeric: "800" },
  { code: "URY", alpha2: "UY", name: "Uruguai", continent: "América do Sul", isoNumeric: "858" },
  { code: "UZB", alpha2: "UZ", name: "Uzbequistão", continent: "Ásia", isoNumeric: "860" },
  { code: "VEN", alpha2: "VE", name: "Venezuela", continent: "América do Sul", isoNumeric: "862" },
  { code: "VNM", alpha2: "VN", name: "Vietnã", continent: "Ásia", isoNumeric: "704" },
  { code: "ZMB", alpha2: "ZM", name: "Zâmbia", continent: "África", isoNumeric: "894" },
  { code: "ZWE", alpha2: "ZW", name: "Zimbábue", continent: "África", isoNumeric: "716" },
];

export const ISO_NUMERIC_TO_ALPHA3: Record<string, string> = Object.fromEntries(
  COUNTRIES_CATALOG.map((c) => [c.isoNumeric, c.code]),
);

export const COUNTRY_BY_CODE: Record<string, CountryOption> = Object.fromEntries(
  COUNTRIES_CATALOG.map((c) => [c.code, c]),
);

export const COUNTRY_CENTER: Record<string, { center: [number, number]; zoom: number }> = {
  BRA: { center: [-51, -14], zoom: 2.5 },
  ARG: { center: [-65, -35], zoom: 2.5 },
  CHL: { center: [-71, -35], zoom: 2.5 },
  COL: { center: [-74, 4], zoom: 3 },
  PER: { center: [-75, -10], zoom: 2.5 },
  MEX: { center: [-102, 23], zoom: 2.5 },
  USA: { center: [-98, 39], zoom: 2 },
  CAN: { center: [-96, 60], zoom: 2 },
  GBR: { center: [-2, 54], zoom: 4 },
  FRA: { center: [2, 46], zoom: 4 },
  DEU: { center: [10, 51], zoom: 4 },
  ESP: { center: [-4, 40], zoom: 4 },
  ITA: { center: [12, 42], zoom: 4 },
  PRT: { center: [-8, 39], zoom: 4 },
  JPN: { center: [138, 36], zoom: 4 },
  CHN: { center: [104, 35], zoom: 2.5 },
  IND: { center: [78, 22], zoom: 3 },
  THA: { center: [101, 13], zoom: 5 },
  AUS: { center: [134, -25], zoom: 2.5 },
  ZAF: { center: [25, -29], zoom: 3 },
};
