import type {
  User,
  Country,
  Pin,
  Friend,
  Challenge,
  ActivitySuggestion,
  Story,
} from "./types";

export const MOCK_PINS: Pin[] = [
  // Brazil - home base
  { id: "p1", type: "home", name: "São Paulo - Home", lat: -23.55, lng: -46.63, countryCode: "BRA", note: "Minha cidade natal" },
  { id: "p2", type: "cafe", name: "Café Floresta", lat: -23.56, lng: -46.65, countryCode: "BRA" },
  { id: "p3", type: "restaurant", name: "Churrascaria do Zé", lat: -22.91, lng: -43.17, countryCode: "BRA" },
  { id: "p4", type: "activity", name: "Cristo Redentor", lat: -22.95, lng: -43.21, countryCode: "BRA" },
  // Thailand
  { id: "p5", type: "travel", name: "Bangkok - Chegada", lat: 13.75, lng: 100.52, countryCode: "THA" },
  { id: "p6", type: "hotel", name: "Lub D Bangkok", lat: 13.73, lng: 100.52, countryCode: "THA" },
  { id: "p7", type: "restaurant", name: "Pad Thai Thip Samai", lat: 13.75, lng: 100.50, countryCode: "THA" },
  { id: "p8", type: "activity", name: "Wat Pho Temple", lat: 13.75, lng: 100.49, countryCode: "THA" },
  { id: "p9", type: "travel", name: "Koh Samui Beach", lat: 9.54, lng: 100.06, countryCode: "THA" },
  { id: "p10", type: "cafe", name: "Mango Tango Café", lat: 13.74, lng: 100.53, countryCode: "THA" },
  // Argentina
  { id: "p11", type: "travel", name: "Buenos Aires", lat: -34.60, lng: -58.38, countryCode: "ARG" },
  { id: "p12", type: "restaurant", name: "La Cabrera Parrilla", lat: -34.58, lng: -58.43, countryCode: "ARG" },
  { id: "p13", type: "hotel", name: "Casa Calma Hotel", lat: -34.59, lng: -58.38, countryCode: "ARG" },
  { id: "p14", type: "activity", name: "Tango en San Telmo", lat: -34.62, lng: -58.37, countryCode: "ARG" },
  { id: "p15", type: "cafe", name: "Café Tortoni", lat: -34.61, lng: -58.38, countryCode: "ARG" },
];

export const MOCK_COUNTRIES: Country[] = [
  {
    code: "BRA",
    name: "Brasil",
    visited: true,
    visitedAt: "2000-01-01",
    pins: MOCK_PINS.filter((p) => p.countryCode === "BRA"),
    flagEmoji: "🇧🇷",
    continent: "South America",
  },
  {
    code: "THA",
    name: "Tailândia",
    visited: true,
    visitedAt: "2023-11-15",
    pins: MOCK_PINS.filter((p) => p.countryCode === "THA"),
    flagEmoji: "🇹🇭",
    continent: "Asia",
  },
  {
    code: "ARG",
    name: "Argentina",
    visited: true,
    visitedAt: "2024-03-20",
    pins: MOCK_PINS.filter((p) => p.countryCode === "ARG"),
    flagEmoji: "🇦🇷",
    continent: "South America",
  },
];

export const MOCK_FRIENDS: Friend[] = [
  { id: "f1", username: "SkyWalker_Ju", character: { skin: "nomad", color: "red", hat: true, backpack: true }, level: 12, xp: 4800, countriesCount: 18, rank: 3, isOnline: true },
  { id: "f2", username: "NomadCarlos", character: { skin: "explorer", color: "green", hat: false, backpack: true }, level: 8, xp: 2100, countriesCount: 9, rank: 7, isOnline: false },
  { id: "f3", username: "WanderLust_Ana", character: { skin: "wanderer", color: "purple", hat: true, backpack: false }, level: 20, xp: 9800, countriesCount: 34, rank: 1, isOnline: true },
  { id: "f4", username: "PixelTraveler", character: { skin: "adventurer", color: "gold", hat: false, backpack: true }, level: 5, xp: 900, countriesCount: 4, rank: 22, isOnline: false },
];

export const MOCK_USER: User = {
  id: "u1",
  username: "Nômade_Fer",
  character: { skin: "adventurer", color: "blue", hat: false, backpack: true },
  level: 7,
  xp: 2340,
  xpToNext: 3000,
  countries: MOCK_COUNTRIES,
  friends: MOCK_FRIENDS,
  rank: 11,
  totalPins: MOCK_PINS.length,
  joinedAt: "2023-08-01",
};

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: "c1",
    title: "Primeiro Passo",
    description: "Visite 5 países diferentes",
    type: "explore",
    progress: 3,
    total: 5,
    xpReward: 500,
    coinReward: 100,
    completed: false,
    icon: "🌍",
    difficulty: "easy",
  },
  {
    id: "c2",
    title: "Foodie Global",
    description: "Adicione 10 pins de restaurantes",
    type: "pin",
    progress: 2,
    total: 10,
    xpReward: 300,
    coinReward: 50,
    completed: false,
    icon: "🍽",
    difficulty: "medium",
  },
  {
    id: "c3",
    title: "Conquistador Asiático",
    description: "Visite 3 países na Ásia",
    type: "explore",
    progress: 1,
    total: 3,
    xpReward: 750,
    coinReward: 150,
    completed: false,
    icon: "🏯",
    difficulty: "medium",
  },
  {
    id: "c4",
    title: "Amigo das Estradas",
    description: "Adicione 3 amigos",
    type: "social",
    progress: 4,
    total: 3,
    xpReward: 200,
    coinReward: 40,
    completed: true,
    icon: "👥",
    difficulty: "easy",
  },
  {
    id: "c5",
    title: "Contador de Histórias",
    description: "Compartilhe 5 stories de viagem",
    type: "story",
    progress: 1,
    total: 5,
    xpReward: 400,
    coinReward: 80,
    completed: false,
    icon: "📸",
    difficulty: "medium",
  },
  {
    id: "c6",
    title: "Marco Polo",
    description: "Visite 20 países",
    type: "explore",
    progress: 3,
    total: 20,
    xpReward: 2000,
    coinReward: 500,
    completed: false,
    icon: "🗺",
    difficulty: "legendary",
  },
];

export const MOCK_SUGGESTIONS: ActivitySuggestion[] = [
  {
    id: "s1",
    title: "Parque Ibirapuera",
    description: "Parque urbano incrível com museus e lagos",
    type: "activity",
    countryCode: "BRA",
    countryName: "Brasil",
    isFree: true,
    rating: 4.8,
    tags: ["natureza", "cultura", "família"],
  },
  {
    id: "s2",
    title: "Chatuchak Weekend Market",
    description: "Maior mercado ao ar livre da Tailândia",
    type: "activity",
    countryCode: "THA",
    countryName: "Tailândia",
    isFree: true,
    rating: 4.7,
    tags: ["compras", "comida", "cultura"],
  },
  {
    id: "s3",
    title: "Cemitério da Recoleta",
    description: "Cemitério histórico e arquitetônico único",
    type: "activity",
    countryCode: "ARG",
    countryName: "Argentina",
    isFree: true,
    rating: 4.6,
    tags: ["história", "arquitetura"],
  },
  {
    id: "s4",
    title: "Muay Thai Experience",
    description: "Aula de Muay Thai autêntica em Bangkok",
    type: "activity",
    countryCode: "THA",
    countryName: "Tailândia",
    isFree: false,
    rating: 4.9,
    tags: ["esporte", "cultura", "aventura"],
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: "st1",
    authorId: "f3",
    authorName: "WanderLust_Ana",
    authorCharacter: { skin: "wanderer", color: "purple", hat: true, backpack: false },
    image: "/stories/thailand-sunset.jpg",
    caption: "Pôr do sol em Koh Samui 🌅 Paraíso existe!",
    countryCode: "THA",
    countryName: "Tailândia",
    likes: 47,
    createdAt: "2024-06-10T18:30:00Z",
    isLiked: true,
  },
  {
    id: "st2",
    authorId: "f1",
    authorName: "SkyWalker_Ju",
    authorCharacter: { skin: "nomad", color: "red", hat: true, backpack: true },
    image: "/stories/argentina-food.jpg",
    caption: "Melhor asado da vida! Buenos Aires 🥩🔥",
    countryCode: "ARG",
    countryName: "Argentina",
    likes: 32,
    createdAt: "2024-06-09T20:15:00Z",
    isLiked: false,
  },
  {
    id: "st3",
    authorId: "u1",
    authorName: "Nômade_Fer",
    authorCharacter: { skin: "adventurer", color: "blue", hat: false, backpack: true },
    image: "/stories/bangkok-temple.jpg",
    caption: "Wat Pho de madrugada. Paz total 🙏",
    countryCode: "THA",
    countryName: "Tailândia",
    likes: 28,
    createdAt: "2024-06-08T06:00:00Z",
    isLiked: false,
  },
];

export const MOCK_RANKING: (Friend & { isMe?: boolean })[] = [
  { ...MOCK_FRIENDS[2], isMe: false },
  { id: "r2", username: "JetSetLara", character: { skin: "explorer", color: "gold", hat: true, backpack: false }, level: 18, xp: 7200, countriesCount: 28, rank: 2, isOnline: true },
  { ...MOCK_FRIENDS[0], isMe: false },
  { id: "r4", username: "BackpackKing", character: { skin: "nomad", color: "blue", hat: false, backpack: true }, level: 15, xp: 5500, countriesCount: 22, rank: 4, isOnline: false },
  { id: "r5", username: "GlobeTrotter99", character: { skin: "wanderer", color: "red", hat: true, backpack: true }, level: 14, xp: 4200, countriesCount: 19, rank: 5, isOnline: true },
  { id: "r6", username: "DesertRose_M", character: { skin: "adventurer", color: "green", hat: false, backpack: false }, level: 13, xp: 3800, countriesCount: 17, rank: 6, isOnline: false },
  { ...MOCK_FRIENDS[1], isMe: false },
  { id: "r8", username: "IslandHopper", character: { skin: "nomad", color: "purple", hat: true, backpack: true }, level: 10, xp: 2800, countriesCount: 13, rank: 8, isOnline: true },
  { id: "r9", username: "NorthernLights", character: { skin: "explorer", color: "blue", hat: false, backpack: false }, level: 9, xp: 2400, countriesCount: 11, rank: 9, isOnline: false },
  { id: "r10", username: "SoukSurfer", character: { skin: "wanderer", color: "gold", hat: true, backpack: true }, level: 8, xp: 1900, countriesCount: 10, rank: 10, isOnline: false },
  { id: "r11", username: "Nômade_Fer", character: MOCK_USER.character, level: MOCK_USER.level, xp: 0, countriesCount: MOCK_USER.countries.length, rank: 11, isOnline: true, isMe: true },
];
